
-- Role Creation
DROP ROLE IF EXISTS 'Database_Administrator', 'Database_Manager', 'Database_Designer', 'Database_Basic_Role';
CREATE ROLE 'Database_Administrator', 'Database_Manager', 'Database_Designer', 'Database_Basic_Role';
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROLE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DROP, DROP ROLE, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'Database_Administrator' WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, LOCK TABLES, SELECT, SHOW DATABASES, SHOW VIEW, TRIGGER, UPDATE ON *.* TO 'Database_Manager' WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE VIEW, INDEX, SHOW DATABASES, SHOW VIEW, TRIGGER ON *.* TO 'Database_Designer';
GRANT SELECT, SHOW DATABASES, SHOW VIEW ON *.* TO 'Database_Basic_Role';

-- Grants for 'Anthea'@'%'
DROP USER IF EXISTS 'Anthea'@'%';
CREATE USER IF NOT EXISTS 'Anthea'@'%';
ALTER USER 'Anthea'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Manager' TO 'Anthea'@'%';

-- Grants for 'Kemelbek'@'%'
DROP USER IF EXISTS 'Kemelbek'@'%';
CREATE USER IF NOT EXISTS 'Kemelbek'@'%';
ALTER USER 'Kemelbek'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Designer' TO 'Kemelbek'@'%';

-- Grants for 'Magdalena'@'%'
DROP USER IF EXISTS 'Magdalena'@'%';
CREATE USER IF NOT EXISTS 'Magdalena'@'%';
ALTER USER 'Magdalena'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Designer' TO 'Magdalena'@'%';

-- Grants for 'Piotr'@'%'
DROP USER IF EXISTS 'Piotr'@'%';
CREATE USER IF NOT EXISTS 'Piotr'@'%';
ALTER USER 'Piotr'@'%' IDENTIFIED WITH 'caching_sha2_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Administrator' TO 'Piotr'@'%';

-- Grants for 'Sai'@'%'
DROP USER IF EXISTS 'Sai'@'%';
CREATE USER IF NOT EXISTS 'Sai'@'%';
ALTER USER 'Sai'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Manager' TO 'Sai'@'%';

-- Grants for 'Yuping'@'%'
DROP USER IF EXISTS 'Yuping'@'%';
CREATE USER IF NOT EXISTS 'Yuping'@'%';
ALTER USER 'Yuping'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Administrator' TO 'Yuping'@'%';

-- Grants for 'Zahid'@'%'
DROP USER IF EXISTS 'Zahid'@'%';
CREATE USER IF NOT EXISTS 'Zahid'@'%';
ALTER USER 'Zahid'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT 'Database_Designer' TO 'Zahid'@'%';
